Repository kyma-incubator/migrate, pull requests merged in 2022-03, with the labels that each got.

#1 Improve argument handling
  README.md
  main.go
Labels: lgtm

#6 Fix v1 resources and arguments
  main.go
Labels: size/S, lgtm

#7 Fix readme
  README.md
  main.go
Labels: size/S, lgtm

#8 Add more arguments
  main.go
Labels: lgtm, size/L

#9 Add integration test
  .gitignore
  go.mod
  go.sum
  main.go
  main_test.go
  testdata/created-cleanup.sh
Labels: lgtm, size/L
